// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildExecutable(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetProjectTree(arg1:string):Promise<main.FileNode>;

export function GetRepoRoot():Promise<string>;

export function GetSettings():Promise<main.UserSettings>;

export function OpenFile(arg1:string):Promise<main.FileResult>;

export function RunProgram(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.UserSettings):Promise<void>;

export function SelectOpenFile():Promise<main.FileResult>;

export function SelectProjectDirectory():Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function StopProgram():Promise<void>;
