// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildExecutable(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildExecutable'](arg1, arg2, arg3);
}

export function GetProjectTree(arg1) {
  return window['go']['main']['App']['GetProjectTree'](arg1);
}

export function GetRepoRoot() {
  return window['go']['main']['App']['GetRepoRoot']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsLspRunning() {
  return window['go']['main']['App']['IsLspRunning']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RunProgram(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunProgram'](arg1, arg2, arg3);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectOpenFile() {
  return window['go']['main']['App']['SelectOpenFile']();
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function SelectSaveFile(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2);
}

export function SendLSP(arg1) {
  return window['go']['main']['App']['SendLSP'](arg1);
}

export function StopProgram() {
  return window['go']['main']['App']['StopProgram']();
}
