package runtime

// modernAliases maps 2026-style names onto existing handlers.
// Classic names stay registered. applyModernAliases skips keys that already exist.
var modernAliases = map[string]string{
	// Window / display
	"setapptitle":       "apptitle",
	"setgraphics3d":     "graphics3d",
	"setgraphics2d":     "graphics2d",
	"setgraphics":       "graphics",
	"deletegraphics":    "endgraphics",
	"closegraphics":     "endgraphics",
	"setcolor":          "color",
	"setclscolor":       "clscolor",
	"setcameraclscolor": "cameraclscolor",
	"setwireframe":      "wireframe",
	"deletewindow":      "freewindow",
	"getwindowclosed":   "windowclosed",

	// Entity get/set
	"setposition":          "positionentity",
	"setrotation":          "rotateentity",
	"setscale":             "scaleentity",
	"getpositionx":         "entityx",
	"getpositiony":         "entityy",
	"getpositionz":         "entityz",
	"getrotationpitch":     "entitypitch",
	"getrotationyaw":       "entityyaw",
	"getrotationroll":      "entityroll",
	"getscalex":            "entityscalex",
	"getscaley":            "entityscaley",
	"getscalez":            "entityscalez",
	"setentitycolor":       "entitycolor",
	"setmaterialcolor":     "entitycolor",
	"setentityalpha":       "entityalpha",
	"setmaterialalpha":     "entityalpha",
	"setmetallicfactor":    "setmetallic",
	"getmetallicfactor":    "getmetallic",
	"setroughnessfactor":   "setroughness",
	"getroughnessfactor":   "getroughness",
	"setocclusionfactor":   "setao",
	"getocclusionfactor":   "getao",
	"enableibl":            "setibl",
	"setbasecolormap":      "setalbedomap",
	"setmaterialshininess": "entityshininess",
	"setentityshininess":   "entityshininess",
	"setentityspecular":    "entityspecular",
	"setmaterialspecular":  "entityspecular",
	"settexture":           "entitytexture",
	"setentitytexture":     "entitytexture",
	"setentityparent":      "entityparent",
	"getentityparent":      "getparent",
	"setentityname":        "nameentity",
	"getentityname":        "entityname",
	"getentityvisible":     "entityvisible",
	"deleteentity":         "freeentity",
	"cloneentity":          "copyentity",
	"createentity":         "createpivot",
	"setentitytype":        "entitytype",
	"setentityradius":      "entityradius",
	"getentitydistance":    "entitydistance",
	"setentitybox":         "entitybox",
	"lookat":               "pointentity",

	// Camera
	"setcamerarange":    "camerarange",
	"setcamerazoom":     "camerazoom",
	"setcamerafov":      "camerazoom",
	"setcameraviewport": "cameraviewport",
	"setcamerafogmode":  "camerafogmode",
	"setcamerafogcolor": "camerafogcolor",
	"setcamerafogrange": "camerafogrange",
	"setcameraprojmode": "cameraprojmode",
	"deletecamera":      "freeentity",
	"setcameraposition": "positionentity",
	"setcamerarotation": "rotateentity",
	"cameralookat":      "pointentity",
	"setcamerafollow":   "camerafollow",
	"cameraprojectx":    "projectedx",
	"cameraprojecty":    "projectedy",
	"cameraprojectz":    "projectedz",
	"cameraunprojectx":  "unprojectx",
	"cameraunprojecty":  "unprojecty",
	"cameraunprojectz":  "unprojectz",

	// Light
	"setlightcolor":     "lightcolor",
	"setlightrange":     "lightrange",
	"setambientlight":   "ambientlight",
	"ambientcolor":      "setambientcolor",
	"deletelight":       "freeentity",
	"setlightdirection": "rotateentity",

	// Input
	"mousebutton":       "mousedown",
	"mousedeltax":       "mousexspeed",
	"mousedeltay":       "mouseyspeed",
	"mousewheel":        "mousez",
	"getmousewheel":     "mousez",
	"getkeystate":       "keydown",
	"getmousebutton":    "mousedown",
	"setmouseposition":  "movemouse",
	"hidecursor":        "hidepointer",
	"showcursor":        "showpointer",
	"rawmousex":         "mousex",
	"rawmousey":         "mousey",
	"rawmousedeltax":    "mousexspeed",
	"rawmousedeltay":    "mouseyspeed",
	"getrawmousex":      "mousex",
	"getrawmousey":      "mousey",
	"getrawmousedeltax": "mousexspeed",
	"getrawmousedeltay": "mouseyspeed",

	// Physics
	"createrigidbody":           "createbody",
	"createrigidbodysphere":     "createbodysphere",
	"createrigidbodybox":        "createbodybox",
	"createrigidbodycapsule":    "createbodycapsule",
	"createpolygon2d":           "createpoly2d",
	"createbodypolygon2d":       "createpoly2d",
	"deleterigidbody":           "freeentity",
	"createcollider":            "createbody",
	"setcollidersize":           "entitybox",
	"setcollidermass":           "setbodymass",
	"setvelocity":               "setbodyvelocity",
	"setlinearvelocity":         "setbodyvelocity",
	"getvelocityx":              "bodyvelocityx",
	"getvelocityy":              "bodyvelocityy",
	"getvelocityz":              "bodyvelocityz",
	"raycast":                   "linepick",
	"getrayhitentity":           "pickedentity",
	"getrayhitx":                "pickedx",
	"getrayhity":                "pickedy",
	"getrayhitz":                "pickedz",
	"getrayhitpositionx":        "pickedx",
	"getrayhitpositiony":        "pickedy",
	"getrayhitpositionz":        "pickedz",
	"setbodyvelocity":           "setbodyvelocity",
	"getbodyvelocity":           "bodyvelocity",
	"getbodyvelocityx":          "bodyvelocityx",
	"getbodyvelocityy":          "bodyvelocityy",
	"getbodyvelocityz":          "bodyvelocityz",
	"getbodyangularvelocityx":   "bodyangularvelocityx",
	"getbodyangularvelocityy":   "bodyangularvelocityy",
	"getbodyangularvelocityz":   "bodyangularvelocityz",
	"setcharactervelocity":      "setcharactervelocity",
	"getcharacteronground":      "characteronground",
	"getphysicscharacter":       "physicscharacter",
	"createcharactercontroller": "createcharactercontroller",
	"setcharactershape":         "setcharactershape",
	"getcharactergroundstate":   "getcharactergroundstate",
	"getcharactergroundnormal":  "getcharactergroundnormal",
	"getcharactercontact":       "getcharactercontact",
	"charactergroundstate":      "getcharactergroundstate",
	"charactergroundnormal":     "getcharactergroundnormal",
	"charactercontact":          "getcharactercontact",
	"createpinjoint2d":          "createpin2d",
	"createdampedspring2d":      "createspring2d",
	"createslidejoint2d":        "createslide2d",
	"getvelocity2dx":            "velocity2dx",
	"getvelocity2dy":            "velocity2dy",
	"getposition2dx":            "position2d",
	"getposition2dy":            "position2dy",
	"getgravityx":               "getgravityx",
	"getgravityy":               "getgravityy",
	"getgravityz":               "getgravityz",
	"setimpulse":                "applyimpulse",
	"setimpulse2d":              "applyimpulse2d",
	"setforce":                  "applyforce",
	"setforce2d":                "applyforce2d",
	"createcar":                 "createcarcontroller",
	"createvehiclecontroller":   "createvehicle",
	"setcarinput":               "setvehicleinput",
	"updatevehicle":             "updatecar",
	"createjet":                 "createjetcontroller",
	"createspaceship":           "createspaceshipcontroller",
	"createboat":                "createboatcontroller",
	"createbike":                "createmotorcyclecontroller",
	"createheli":                "createhelicoptercontroller",
	"createhover":               "createhovercraftcontroller",
	"createsub":                 "createsubmarinecontroller",
	"createtank":                "createtankcontroller",
	"createdrone":               "createdronecontroller",
	"createglider":              "createglidercontroller",
	"createski":                 "createskicontroller",
	"createwaterski":            "createwaterskicontroller",
	"applytorqueat":             "applytorque",
	"getcharactergroundnormalx": "charactergroundnormalx",
	"getcharactergroundnormaly": "charactergroundnormaly",
	"getcharactergroundnormalz": "charactergroundnormalz",

	// Animation
	"loadanimation":      "loadanimmesh",
	"playanimation":      "animate",
	"stopanimation":      "stopanim",
	"setanimationspeed":  "animate",
	"setanimationtime":   "setanimtime",
	"setanimationframe":  "setanimtime",
	"getanimationtime":   "animtime",
	"getanimationframe":  "animtime",
	"getanimationlength": "animlength",
	"setanimation":       "setanimseq",
	"blendanimation":     "setanimblend",
	"savescene":          "scenesave",
	"loadscenejson":      "sceneload",
	"setentityshader":    "setshader",
	"getentityshader":    "entityshader",

	// Audio
	"deletesound":    "freesound",
	"loadmusic":      "loadsound",
	"playmusic":      "loopsound",
	"stopmusic":      "stopsound",
	"setmusicvolume": "setsoundvolume",

	// 2D
	"setspriteposition": "positionsprite",
	"setspriterotation": "rotatesprite",
	"setspritescale":    "scalesprite",
	"getspritex":        "spritex",
	"getspritey":        "spritey",
	"deletesprite":      "hidesprite",

	// Particles / scene
	"setemitterrate":      "emitterrate",
	"setemittermax":       "emittermax",
	"setemitterlife":      "emitterlife",
	"setemitterspeed":     "emitterspeed",
	"setemittersize":      "emittersize",
	"setemittercolor":     "emittercolor",
	"setemittervelocity":  "emittervelocity",
	"setemittergravity":   "emittergravity",
	"setemitterwind":      "emitterwind",
	"setemittercone":      "emittercone",
	"setemitterdrag":      "emitterdrag",
	"setemitterduration":  "emitterduration",
	"setemitterloop":      "emitterloop",
	"setemitterarea":      "emitterarea",
	"setemitterparticle":  "emitterparticle",
	"setemitterposition":  "positionemitter",
	"setemitterparent":    "parentemitter",
	"setemitterspread":    "emittercone",
	"deleteemitter":       "freeemitter",
	"setpak":              "openpak",
	"getweather":          "weather",
	"getweatherintensity": "weatherintensity",
	"getweatherwetness":   "weatherwetness",
	"setwetness":          "setweatherwetness",
	"lightningstrike":     "strikelightning",
	"createclouds":        "createvolumetricclouds",
	"setcloudcover":       "setcloudcoverage",
	"setcamerafogdensity": "camerafogdensity",
	"createboxmesh":       "createbox",
	"createcapsulemesh":   "createcapsule",

	// Time
	"deletetimer":   "freetimer",
	"gettimerticks": "timerticks",

	// Files
	"fileexists": "filetype",

	// Xform
	"gettransformedx": "tformedx",
	"gettransformedy": "tformedy",
	"gettransformedz": "tformedz",
	"cameraproject":   "projectedx",
	"cameraunproject": "unprojectx",

	// Net (already modern; extra Get/Set)
	"getnetmsg":           "netmsg",
	"getnetpeer":          "netpeer",
	"getnetevent":         "netevent",
	"getnetpeercount":     "netpeercount",
	"getnetconnected":     "netconnected",
	"getnetbackend":       "netbackend",
	"getnetplayername":    "netplayername",
	"getnetlocalid":       "netlocalid",
	"getnetroom":          "netroom",
	"getnetrtt":           "netrtt",
	"getnettick":          "nettick",
	"createhost":          "createhost",
	"createnetworkhost":   "createhost",
	"createnetworkclient": "connecthost",
	"connectnetwork":      "connecthost",
	"sendnetwork":         "sendnet",
	"sendnetworkmessage":  "sendnetworkmessage",
	"disconnectnetwork":   "disconnectnetwork",
	"closenetworkhost":    "closehost",
	"closenetwork":        "closehost",
	"pollnet":             "pollnetwork",
	"getneteventtype":     "getneteventtype",
	"getnetworkeventtype": "getneteventtype",
	"getnetworkpeerid":    "getnetworkpeerid",
	"getnetworkdata":      "getnetworkdata",
	"getnetpeerip":        "getnetpeerip",
	"getnetworkpeerip":    "getnetpeerip",
	"deletehost":          "closehost",

	// Physics query
	"getphysicsbackend": "physicsbackend",

	// Large-world / terrain / water / jobs / editor
	"setshadowresolution":  "shadowmapsize",
	"getshadowresolution":  "shadowmapsize",
	"enableshadowcaching":  "enableshadowcache",
	"setshadowcaching":     "enableshadowcache",
	"castshadow":           "entitycastshadow",
	"setcastshadow":        "entitycastshadow",
	"receiveshadow":        "entityreceiveshadow",
	"setreceiveshadow":     "entityreceiveshadow",
	"shadowdistance":       "setshadowdistance",
	"getterrainheight":     "terrainheight",
	"getterrainfrequency":  "getterrainfreq",
	"setterrainfrequency":  "setterrainfreq",
	"getterrainslope":      "terrainslope",
	"getcloudcover":        "getcloudcoverage",
	"getgeooriginlon":      "geooriginlon",
	"getgeooriginlat":      "geooriginlat",
	"getgeoscale":          "geoscale",
	"getgeoprojectx":       "geoproject",
	"geoprojectx":          "geoproject",
	"getgeoprojectz":       "geoprojectz",
	"getgeounproject":      "geounproject",
	"getgeounprojectlon":   "geounproject",
	"geounprojectlon":      "geounproject",
	"getgeounprojectlat":   "geounprojectlat",
	"getgeolon":            "geounproject",
	"getgeolat":            "geounprojectlat",
	"getgeotilex":          "geotilex",
	"getgeotiley":          "geotiley",
	"getgeotilez":          "geotilez",
	"getgeotmsy":           "geotmsy",
	"getgeojsoncount":      "geojsoncount",
	"getgeoheight":         "geoheight",
	"getterrainchunkcount": "terrainchunkcount",
	"getheightmapwidth":    "heightmapwidth",
	"getheightmapheight":   "heightmapheight",
	"loadheightmapdata":    "importheightmap",
	"getwaterheight":       "waterheight",
	"getstreamchunkcount":  "streamchunkcount",
	"getstreamoriginx":     "streamoriginx",
	"getstreamoriginz":     "streamoriginz",
	"getstreamradius":      "setstreamradius",
	"getchunkloaded":       "chunkloaded",
	"getjobcount":          "jobcount",
	"getjobqueue":          "jobqueue",
	"getstatsfps":          "statsfps",
	"getstatsdraws":        "statsdraws",
	"getstatschunks":       "statschunks",
	"getstatsjobs":         "statsjobs",
	"getentitycount":       "entitycount",
	"getentitybyindex":     "entitybyindex",
	"getinstancecount":     "instancecount",
	"setinstancecount":     "instancecount",
	"getinstanceentity":    "instanceentity",
	"setphysicsasync":      "physicsasync",
	"getphysicsasync":      "physicsasync",
	"setphysicsthreads":    "physicsthreads",
	"getphysicsthreads":    "physicsthreads",
	"sleepbody":            "bodysleep",
	"wakebody":             "bodywake",
	"setwaterreflection":   "enablewaterreflection",
	"setwaterrefraction":   "enablewaterrefraction",
	"setwaterdudvmap":      "setwaterdudv",
	"setwaterwinddir":      "setwaterwind",
	"setwatermode":         "setwaterstyle",
	"setwaterwave":         "setwaterwaves",
	"enablewatercaustics":  "setwatercaustics",
	"enablewaterssr":       "setwaterssr",
	"setwaterambient":      "setwaterambientsound",
	"getnavmaxslope":       "setnavmaxslope",
	"setcrowddestination":  "crowdsetdestination",
	"addcrowdagent":        "crowdaddagent",
	"createinstanced":      "createinstancedmesh",
	"getgamepaddeadzone":   "gamepaddeadzone",
	"getwidgettext":        "widgettext",
	"getwidgetvalue":       "widgetvalue",

	"getglversion":         "glversion",
	"getglmajor":           "glmajor",
	"getglminor":           "glminor",
	"getglrenderer":        "glrenderer",
	"getglhascompute":      "glhascompute",
	"getglhasssbo":         "glhasssbo",
	"getglhasubo":          "glhasubo",
	"getglhasinstancing":   "glhasinstancing",
	"getglhasgeometry":     "glhasgeometry",
	"getglhastessellation": "glhastessellation",
	"setgpuinstances":      "enablegpuinstances",
	"settessellation":      "enabletessellation",
	"getcomputelog":        "computelog",
	"getshaderlog":         "shaderlog",
	"mass":                 "setmass",
	"bodymass":             "setmass",

	// Character Controllers & Vehicles
	"createfps":        "createfpscontroller",
	"createtps":        "createtpscontroller",
	"createtopdown":    "createtopdowncontroller",
	"createplatformer": "createplatformercontroller",
	"createmech":       "createmechcontroller",
	"createlander":     "createlandercontroller",
	"createjetski":     "createjetskicontroller",

	// Camera & Gameplay
	"springarm":      "cameraspringarm",
	"screenshake":    "camerashake",
	"smoothlook":     "camerasmoothlook",
	"mathlerp":       "lerp",
	"mathclamp":      "clamp",
	"mathsmoothdamp": "smoothdamp",
	"dist3d":         "distance3d",
	"dist2d":         "distance2d",
	"sound3d":        "playsound3d",
}

func applyModernAliases(m map[string]cmd) {
	for modern, classic := range modernAliases {
		if _, exists := m[modern]; exists {
			continue
		}
		if h, ok := m[classic]; ok {
			m[modern] = h
		}
	}
}

func countModernAliases(m map[string]cmd) int {
	n := 0
	for modern, classic := range modernAliases {
		if _, ok := m[modern]; ok {
			if modern != classic {
				n++
			}
		}
	}
	return n
}
