// Package transpile converts BitShin BASIC AST into native Go source code
// for high-performance Ahead-Of-Time (AOT) compilation without interpreter overhead.
package transpile

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"bitshinbasic/internal/ast"
	"bitshinbasic/internal/lex"
	"bitshinbasic/internal/syntax"
)

// Options configures the Go code generator.
type Options struct {
	PackageName  string
	IsExecutable bool // Generate func main() if true, or func Run(w *runtime.World) error if false
	SourceFile   string
}

// Transpile converts a parsed Program AST into formatted Go code.
func Transpile(prog *ast.Program, opt Options) (string, error) {
	if opt.PackageName == "" {
		opt.PackageName = "main"
	}

	var buf bytes.Buffer
	w := &writer{buf: &buf, indent: 0}

	w.line("// Code generated by BitShin Modern Blitz Transpiler. DO NOT EDIT.")
	if opt.SourceFile != "" {
		w.line("// Source: " + opt.SourceFile)
	}
	w.line("package " + opt.PackageName)
	w.line("")
	w.line("import (")
	w.line("\t\"fmt\"")
	w.line("\t\"math\"")
	w.line("\t\"math/rand/v2\"")
	w.line("\t\"os\"")
	w.line("\t\"path/filepath\"")
	w.line("\t\"strings\"")
	w.line("\t\"time\"")
	w.line("")
	w.line("\t\"bitshinbasic/internal/runtime\"")
	w.line("\t\"bitshinbasic/internal/syntax\"")
	w.line("\t\"bitshinbasic/internal/value\"")
	w.line(")")
	w.line("")

	// Runtime helpers
	emitHelpers(w)

	// Collect types, functions, data, and top-level statements.
	// Namespaces are flattened (Util.Sum). Methods become functions with a Self parameter.
	typeDecls, funcs, methods, topStmts, dataExprs, namespaces := collectProgram(prog.Stmts)

	globals := map[string]bool{}
	for _, s := range topStmts {
		collectVars(s, globals)
	}
	collectExplicitGlobals(prog.Stmts, globals)
	w.userFn = map[string]bool{}
	w.types = map[string]*ast.TypeDecl{}
	w.namespaces = namespaces
	w.intNames, w.strNames = suffixNames(prog.Stmts)
	for _, td := range typeDecls {
		w.types[lex.IdentKey(td.Name)] = td
	}
	for _, fn := range funcs {
		w.userFn[lex.IdentKey(fn.Name)] = true
		locals := collectFuncLocals(fn, globals)
		noteGlobals(fn.Body, locals, globals)
	}

	if len(globals) > 0 {
		names := make([]string, 0, len(globals))
		for name := range globals {
			names = append(names, name)
		}
		sort.Strings(names)
		w.line("var (")
		for _, name := range names {
			w.line("\t" + name + " value.Value")
		}
		w.line(")")
		w.line("")
	}

	// Emit user functions
	for _, fn := range funcs {
		emitFunction(w, fn, globals)
		w.line("")
	}

	// Emit entry point. Play pumps Flip on the window thread.
	if opt.IsExecutable {
		w.line("func main() {")
		w.indent++
		w.line("workDir := \".\"")
		w.line("if len(os.Args) > 0 { workDir = filepath.Dir(os.Args[0]) }")
		w.line("w := runtime.New(workDir)")
		if opt.SourceFile != "" {
			w.line(fmt.Sprintf("w.SetScript(filepath.Join(workDir, %q))", opt.SourceFile))
		}
		emitMethodTable(w, methods, funcs)
		w.line("w.Play(func(w *runtime.World) {")
		w.indent++
	} else {
		w.line("func Run(w *runtime.World) error {")
		w.indent++
		emitMethodTable(w, methods, funcs)
		w.line("w.Play(func(w *runtime.World) {")
		w.indent++
	}

	// Type registrations
	for _, td := range typeDecls {
		fields := make([]string, len(td.Fields))
		for i, f := range td.Fields {
			fields[i] = fmt.Sprintf("%q", strings.ToLower(f.Name))
		}
		w.line(fmt.Sprintf("_bb_types[%q] = []string{%s}", strings.ToLower(td.Name), strings.Join(fields, ", ")))
	}
	if len(typeDecls) > 0 {
		w.line("")
	}

	// Data initialization
	for _, de := range dataExprs {
		w.line(fmt.Sprintf("_bb_data = append(_bb_data, %s)", w.emitExpr(de, "w")))
	}
	if len(dataExprs) > 0 {
		w.line("")
	}

	for _, s := range topStmts {
		emitStmt(w, s, "w")
	}

	w.indent--
	w.line("})")
	if !opt.IsExecutable {
		w.line("return nil")
	}
	w.indent--
	w.line("}")

	raw := buf.Bytes()
	formatted, err := format.Source(raw)
	if err != nil {
		// Return raw code with the error so it can be debugged
		return string(raw), fmt.Errorf("transpiled code formatting error: %w\n---\n%s", err, string(raw))
	}
	return string(formatted), nil
}

type writer struct {
	buf        *bytes.Buffer
	indent     int
	inFunc     bool
	locals     map[string]bool
	userFn     map[string]bool
	types      map[string]*ast.TypeDecl
	namespaces map[string]bool
	intNames   map[string]bool
	strNames   map[string]bool
}

func (w *writer) line(s string) {
	if s == "" {
		w.buf.WriteString("\n")
		return
	}
	for i := 0; i < w.indent; i++ {
		w.buf.WriteString("\t")
	}
	w.buf.WriteString(s)
	w.buf.WriteString("\n")
}

func emitHelpers(w *writer) {
	w.line("var _bb_start = time.Now()")
	w.line("var _bb_rng = rand.New(rand.NewPCG(uint64(time.Now().UnixNano()), 0xa0761d6478bd642f))")
	w.line("var _bb_types = map[string][]string{}")
	w.line("var _bb_data = []value.Value{}")
	w.line("var _bb_data_pc = 0")
	w.line("var _bb_err error")
	w.line("var _bb_live bool")
	w.line("")
	w.line("func _bb_new_struct(typeName string) value.Value {")
	w.line("\tfields, ok := _bb_types[strings.ToLower(typeName)]")
	w.line("\tif !ok { return value.StructOf(typeName, nil) }")
	w.line("\treturn value.StructOf(typeName, fields)")
	w.line("}")
	w.line("func _bb_read_data() value.Value {")
	w.line("\tif _bb_data_pc >= len(_bb_data) { return value.Num(0) }")
	w.line("\tv := _bb_data[_bb_data_pc]")
	w.line("\t_bb_data_pc++")
	w.line("\treturn v")
	w.line("}")
	w.line("func _bb_case_range(val, low, high value.Value) bool {")
	w.line("\treturn value.Cmp(val, low) >= 0 && value.Cmp(val, high) <= 0")
	w.line("}")
	w.line("func _bb_deg(d float64) float64 { return d * math.Pi / 180.0 }")
	w.line("func _bb_rad(r float64) float64 { return r * 180.0 / math.Pi }")
	w.line("func _bb_bool(b bool) value.Value { if b { return value.Num(1) }; return value.Num(0) }")
	w.line("func _bb_sub(a, b value.Value) value.Value { return value.Num(a.Number() - b.Number()) }")
	w.line("func _bb_mul(a, b value.Value) value.Value { return value.Num(a.Number() * b.Number()) }")
	w.line("func _bb_div(a, b value.Value) value.Value {")
	w.line("\td := b.Number()")
	w.line("\tif d == 0 { return value.Num(0) }")
	w.line("\treturn value.Num(a.Number() / d)")
	w.line("}")
	w.line("func _bb_mod(a, b value.Value) value.Value {")
	w.line("\td := b.Number()")
	w.line("\tif d == 0 { return value.Num(0) }")
	w.line("\treturn value.Num(math.Mod(a.Number(), d))")
	w.line("}")
	w.line("func _bb_and(l, r func() value.Value) value.Value {")
	w.line("\tif !l().IsTrue() { return value.Num(0) }")
	w.line("\tif r().IsTrue() { return value.Num(1) }")
	w.line("\treturn value.Num(0)")
	w.line("}")
	w.line("func _bb_or(l, r func() value.Value) value.Value {")
	w.line("\tif l().IsTrue() { return value.Num(1) }")
	w.line("\tif r().IsTrue() { return value.Num(1) }")
	w.line("\treturn value.Num(0)")
	w.line("}")
	w.line("func _bb_xor(l, r value.Value) value.Value {")
	w.line("\tif l.IsTrue() != r.IsTrue() { return value.Num(1) }")
	w.line("\treturn value.Num(0)")
	w.line("}")
	w.line("func _bb_escape_arg(v value.Value) bool {")
	w.line("\tif v.Kind == value.KindNum { n := v.Int(); return n == 1 }")
	w.line("\ts := strings.ToLower(strings.TrimSpace(v.String()))")
	w.line("\treturn s == \"1\" || s == \"escape\" || s == \"esc\" || s == \"key_escape\"")
	w.line("}")
	w.line("func _bb_call(w *runtime.World, name string, args ...value.Value) value.Value {")
	w.line("\tif !_bb_live {")
	w.line("\t\tswitch name {")
	w.line("\t\tcase \"windowshouldclose\":")
	w.line("\t\t\treturn value.Num(0)")
	w.line("\t\tcase \"keydown\", \"keyhit\":")
	w.line("\t\t\tif len(args) > 0 && _bb_escape_arg(args[0]) { return value.Num(0) }")
	w.line("\t\t}")
	w.line("\t}")
	w.line("\tres, err := w.Call(name, args)")
	w.line("\tif err != nil {")
	w.line("\t\t_bb_err = err")
	w.line("\t}")
	w.line("\tif name == \"flip\" { _bb_live = true }")
	w.line("\treturn res")
	w.line("}")
	w.line("func _bb_dot(w *runtime.World, recv value.Value, method string, args ...value.Value) value.Value {")
	w.line("\tkey := recv.TypeName + \".\" + strings.ToLower(method)")
	w.line("\tif recv.Kind == value.KindStruct {")
	w.line("\t\tif fn, ok := _bb_methods[key]; ok {")
	w.line("\t\t\treturn fn(w, recv, args)")
	w.line("\t\t}")
	w.line("\t}")
	w.line("\tif cmd, ok := syntax.ResolveMethod(method); ok {")
	w.line("\t\tfull := make([]value.Value, 0, len(args)+1)")
	w.line("\t\tfull = append(full, recv)")
	w.line("\t\tfull = append(full, args...)")
	w.line("\t\treturn _bb_call(w, cmd, full...)")
	w.line("\t}")
	w.line("\tif fn, ok := _bb_methods[key]; ok {")
	w.line("\t\treturn fn(w, recv, args)")
	w.line("\t}")
	w.line("\treturn value.Num(0)")
	w.line("}")
	w.line("func _bb_hex(v value.Value) value.Value {")
	w.line("\tif v.Kind == value.KindNum { return v }")
	w.line("\tn, err := syntax.ParseHexInt(v.String())")
	w.line("\tif err != nil { return value.Num(0) }")
	w.line("\treturn value.Num(float64(n))")
	w.line("}")
	w.line("func _bb_map_set(m value.Value, key, val value.Value) value.Value {")
	w.line("\tif m.Kind != value.KindMap { return value.Num(0) }")
	w.line("\tm.SetField(key.String(), val)")
	w.line("\treturn value.Num(1)")
	w.line("}")
	w.line("func _bb_map_get(m value.Value, key value.Value) value.Value {")
	w.line("\tif m.Kind != value.KindMap { return value.Num(0) }")
	w.line("\tif v, ok := m.Field(key.String()); ok { return v }")
	w.line("\treturn value.Num(0)")
	w.line("}")
	w.line("func _bb_map_has(m value.Value, key value.Value) value.Value {")
	w.line("\tif m.Kind != value.KindMap { return value.Num(0) }")
	w.line("\tif _, ok := m.Field(key.String()); ok { return value.Num(1) }")
	w.line("\treturn value.Num(0)")
	w.line("}")
	w.line("func _bb_map_delete(m value.Value, key value.Value) value.Value {")
	w.line("\tif m.Kind != value.KindMap || m.Fields == nil { return value.Num(0) }")
	w.line("\tdelete(m.Fields, strings.ToLower(strings.TrimRight(key.String(), \"$#%\")))")
	w.line("\treturn value.Num(1)")
	w.line("}")
	w.line("func _bb_map_count(m value.Value) value.Value {")
	w.line("\tif m.Kind != value.KindMap { return value.Num(0) }")
	w.line("\treturn value.Num(float64(len(m.Fields)))")
	w.line("}")
	w.line("type _bbMach struct {")
	w.line("\tcur string")
	w.line("\tfn  map[string]string")
	w.line("}")
	w.line("var _bb_machs = map[int]*_bbMach{}")
	w.line("var _bb_mach_n int")
	w.line("var _bb_callbacks = map[string]func(*runtime.World) value.Value{}")
	w.line("var _bb_methods = map[string]func(*runtime.World, value.Value, []value.Value) value.Value{}")
	w.line("func _bb_arraysize(a value.Value, dim int) value.Value {")
	w.line("\tif a.Kind != value.KindArray { return value.Num(0) }")
	w.line("\tif dim > 0 { dim-- }")
	w.line("\treturn value.Num(float64(a.DimSize(dim)))")
	w.line("}")
	w.line("func _bb_left(s string, n int) value.Value {")
	w.line("\tif n < 0 { n = 0 }")
	w.line("\tif n > len(s) { n = len(s) }")
	w.line("\treturn value.Str(s[:n])")
	w.line("}")
	w.line("func _bb_right(s string, n int) value.Value {")
	w.line("\tif n < 0 { n = 0 }")
	w.line("\tif n > len(s) { n = len(s) }")
	w.line("\treturn value.Str(s[len(s)-n:])")
	w.line("}")
	w.line("func _bb_mid(s string, start, n int) value.Value {")
	w.line("\tstart--")
	w.line("\tif start < 0 { start = 0 }")
	w.line("\tif start > len(s) { return value.Str(\"\") }")
	w.line("\tend := start + n")
	w.line("\tif n == 0 || end > len(s) { end = len(s) }")
	w.line("\treturn value.Str(s[start:end])")
	w.line("}")
	w.line("func _bb_print(w *runtime.World, args ...value.Value) value.Value {")
	w.line("\tparts := make([]string, len(args))")
	w.line("\tfor i, a := range args { parts[i] = a.String() }")
	w.line("\tline := strings.Join(parts, \" \")")
	w.line("\tfmt.Println(line)")
	w.line("\tif w != nil { _, _ = w.Call(\"hudprint\", []value.Value{value.Str(line)}) }")
	w.line("\treturn value.Num(0)")
	w.line("}")
	w.line("")
	emitLangHelpers(w)
}

func sanitizeIdent(name string) string {
	key := lex.IdentKey(name)
	key = strings.ReplaceAll(key, ".", "_")
	var b strings.Builder
	for _, r := range key {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	s := b.String()
	if s == "type" || s == "var" || s == "func" || s == "range" || s == "map" || s == "chan" || s == "select" || s == "case" || s == "default" {
		s = "v_" + s
	}
	return "v_" + s
}

func sanitizeFn(name string) string {
	key := lex.IdentKey(name)
	key = strings.ReplaceAll(key, ".", "_")
	return "fn_" + key
}

func (w *writer) sym(name string) string {
	id := sanitizeIdent(name)
	if w.inFunc && w.locals[id] {
		return "loc_" + id
	}
	return id
}

func isConstIdent(name string) bool {
	k := lex.IdentKey(name)
	switch k {
	case "true", "false", "yes", "no", "null", "pi":
		return true
	}
	if _, ok := syntax.KeyConstants[k]; ok {
		return true
	}
	if _, ok := syntax.WeatherConstants[k]; ok {
		return true
	}
	if _, ok := syntax.NetConstants[k]; ok {
		return true
	}
	if _, ok := syntax.PhysicsConstants[k]; ok {
		return true
	}
	return false
}

func collectProgram(stmts []ast.Stmt) (
	typeDecls []*ast.TypeDecl,
	funcs []*ast.FuncDecl,
	methods []*ast.FuncDecl,
	top []ast.Stmt,
	data []ast.Expr,
	namespaces map[string]bool,
) {
	namespaces = map[string]bool{}
	var walk func([]ast.Stmt, string)
	walk = func(list []ast.Stmt, prefix string) {
		qual := func(name string) string {
			if prefix == "" {
				return name
			}
			return prefix + "." + name
		}
		for _, s := range list {
			switch t := s.(type) {
			case *ast.TypeDecl:
				td := *t
				td.Name = qual(t.Name)
				typeDecls = append(typeDecls, &td)
				for _, m := range t.Methods {
					if m == nil {
						continue
					}
					md := *m
					md.Name = td.Name + "." + m.Name
					md.Params = append([]string{"Self"}, m.Params...)
					funcs = append(funcs, &md)
					methods = append(methods, &md)
				}
			case *ast.MethodDecl:
				md := &ast.FuncDecl{
					Src: t.Src, Name: qual(t.Recv) + "." + t.Name,
					Params: append([]string{"Self"}, t.Params...), Defaults: t.Defaults, Body: t.Body,
				}
				funcs = append(funcs, md)
				methods = append(methods, md)
			case *ast.FuncDecl:
				fn := *t
				fn.Name = qual(t.Name)
				funcs = append(funcs, &fn)
			case *ast.NamespaceDecl:
				namespaces[lex.IdentKey(qual(t.Name))] = true
				walk(t.Stmts, qual(t.Name))
			case *ast.DataStmt:
				data = append(data, t.Values...)
			default:
				if prefix == "" {
					top = append(top, s)
				}
			}
		}
	}
	walk(stmts, "")
	return typeDecls, funcs, methods, top, data, namespaces
}

func emitMethodTable(w *writer, methods, funcs []*ast.FuncDecl) {
	for _, m := range methods {
		w.line(fmt.Sprintf("_bb_methods[%q] = func(w *runtime.World, self value.Value, args []value.Value) value.Value {", lex.IdentKey(m.Name)))
		w.indent++
		call := []string{"w", "self"}
		for i := 1; i < len(m.Params); i++ {
			w.line(fmt.Sprintf("var a%d value.Value", i-1))
			w.line(fmt.Sprintf("if len(args) > %d { a%d = args[%d] }", i-1, i-1, i-1))
			call = append(call, fmt.Sprintf("a%d", i-1))
		}
		w.line(fmt.Sprintf("return %s(%s)", sanitizeFn(m.Name), strings.Join(call, ", ")))
		w.indent--
		w.line("}")
	}
	for _, fn := range funcs {
		if len(fn.Params) != 0 {
			continue
		}
		if strings.Contains(fn.Name, ".") && strings.HasSuffix(strings.ToLower(fn.Name), ".self") {
			continue
		}
		// Zero-arg functions can be state-machine callbacks (AddState name string).
		isMethod := false
		for _, m := range methods {
			if m == fn {
				isMethod = true
				break
			}
		}
		if isMethod {
			continue
		}
		w.line(fmt.Sprintf("_bb_callbacks[%q] = %s", lex.IdentKey(fn.Name), sanitizeFn(fn.Name)))
	}
}

func collectVars(stmt ast.Stmt, vars map[string]bool) {
	if stmt == nil {
		return
	}
	switch s := stmt.(type) {
	case *ast.AssignStmt:
		vars[sanitizeIdent(s.Name)] = true
	case *ast.LocalStmt:
		for _, name := range s.Names {
			vars[sanitizeIdent(name)] = true
		}
	case *ast.GlobalStmt:
		for _, name := range s.Names {
			vars[sanitizeIdent(name)] = true
		}
	case *ast.DimStmt:
		vars[sanitizeIdent(s.Name)] = true
	case *ast.ForStmt:
		vars[sanitizeIdent(s.Var)] = true
		for _, b := range s.Body {
			collectVars(b, vars)
		}
	case *ast.IfStmt:
		for _, b := range s.Then {
			collectVars(b, vars)
		}
		for _, el := range s.ElseIf {
			for _, b := range el.Body {
				collectVars(b, vars)
			}
		}
		for _, b := range s.Else {
			collectVars(b, vars)
		}
	case *ast.WhileStmt:
		for _, b := range s.Body {
			collectVars(b, vars)
		}
	case *ast.RepeatStmt:
		for _, b := range s.Body {
			collectVars(b, vars)
		}
	case *ast.SelectStmt:
		for _, c := range s.Cases {
			for _, b := range c.Body {
				collectVars(b, vars)
			}
		}
		for _, b := range s.Default {
			collectVars(b, vars)
		}
	case *ast.ReadStmt:
		for _, name := range s.Names {
			vars[sanitizeIdent(name)] = true
		}
	case *ast.ConstStmt:
		for _, name := range s.Names {
			vars[sanitizeIdent(name)] = true
		}
	case *ast.EnumStmt:
		for _, name := range s.Names {
			vars[sanitizeIdent(name)] = true
			if s.Name != "" {
				vars[sanitizeIdent(s.Name+"_"+name)] = true
			}
		}
	case *ast.TryStmt:
		if s.ErrVar != "" {
			vars[sanitizeIdent(s.ErrVar)] = true
		}
		for _, b := range s.Body {
			collectVars(b, vars)
		}
		for _, b := range s.Catch {
			collectVars(b, vars)
		}
	}
}

func collectExplicitGlobals(stmts []ast.Stmt, g map[string]bool) {
	for _, s := range stmts {
		switch n := s.(type) {
		case *ast.GlobalStmt:
			for _, name := range n.Names {
				g[sanitizeIdent(name)] = true
			}
		case *ast.EnumStmt:
			for _, name := range n.Names {
				g[sanitizeIdent(name)] = true
				if n.Name != "" {
					g[sanitizeIdent(n.Name+"_"+name)] = true
				}
			}
		case *ast.FuncDecl:
			collectExplicitGlobals(n.Body, g)
		case *ast.IfStmt:
			collectExplicitGlobals(n.Then, g)
			for _, el := range n.ElseIf {
				collectExplicitGlobals(el.Body, g)
			}
			collectExplicitGlobals(n.Else, g)
		case *ast.WhileStmt:
			collectExplicitGlobals(n.Body, g)
		case *ast.ForStmt:
			collectExplicitGlobals(n.Body, g)
		case *ast.RepeatStmt:
			collectExplicitGlobals(n.Body, g)
		case *ast.SelectStmt:
			for _, c := range n.Cases {
				collectExplicitGlobals(c.Body, g)
			}
			collectExplicitGlobals(n.Default, g)
		case *ast.TryStmt:
			collectExplicitGlobals(n.Body, g)
			collectExplicitGlobals(n.Catch, g)
		}
	}
}

func collectFuncLocals(fn *ast.FuncDecl, globals map[string]bool) map[string]bool {
	locals := map[string]bool{}
	for _, p := range fn.Params {
		locals[sanitizeIdent(p)] = true
	}
	var walk func([]ast.Stmt)
	walk = func(stmts []ast.Stmt) {
		for _, s := range stmts {
			switch n := s.(type) {
			case *ast.LocalStmt:
				for _, name := range n.Names {
					locals[sanitizeIdent(name)] = true
				}
			case *ast.ConstStmt:
				for _, name := range n.Names {
					locals[sanitizeIdent(name)] = true
				}
			case *ast.ForStmt:
				locals[sanitizeIdent(n.Var)] = true
				walk(n.Body)
			case *ast.DimStmt:
				locals[sanitizeIdent(n.Name)] = true
			case *ast.AssignStmt:
				names := n.Names
				if len(names) == 0 {
					names = []string{n.Name}
				}
				for _, name := range names {
					id := sanitizeIdent(name)
					if !globals[id] {
						locals[id] = true
					}
				}
			case *ast.ReadStmt:
				for _, name := range n.Names {
					id := sanitizeIdent(name)
					if !globals[id] {
						locals[id] = true
					}
				}
			case *ast.TryStmt:
				if n.ErrVar != "" {
					locals[sanitizeIdent(n.ErrVar)] = true
				}
				walk(n.Body)
				walk(n.Catch)
			case *ast.IfStmt:
				walk(n.Then)
				for _, el := range n.ElseIf {
					walk(el.Body)
				}
				walk(n.Else)
			case *ast.WhileStmt:
				walk(n.Body)
			case *ast.RepeatStmt:
				walk(n.Body)
			case *ast.SelectStmt:
				for _, c := range n.Cases {
					walk(c.Body)
				}
				walk(n.Default)
			}
		}
	}
	walk(fn.Body)
	return locals
}

func noteGlobals(stmts []ast.Stmt, locals, globals map[string]bool) {
	var walkExpr func(ast.Expr)
	var walkStmts func([]ast.Stmt)
	walkExpr = func(e ast.Expr) {
		if e == nil {
			return
		}
		switch n := e.(type) {
		case *ast.IdentExpr:
			if isConstIdent(n.Name) {
				return
			}
			id := sanitizeIdent(n.Name)
			if !locals[id] {
				globals[id] = true
			}
		case *ast.IndexExpr:
			if !isConstIdent(n.Name) {
				id := sanitizeIdent(n.Name)
				if !locals[id] {
					globals[id] = true
				}
			}
			for _, a := range n.Index {
				walkExpr(a)
			}
		case *ast.UnaryExpr:
			walkExpr(n.X)
		case *ast.BinaryExpr:
			walkExpr(n.Left)
			walkExpr(n.Right)
		case *ast.FieldExpr:
			walkExpr(n.X)
		case *ast.MethodExpr:
			walkExpr(n.X)
			for _, a := range n.Args {
				walkExpr(a)
			}
		case *ast.CallExpr:
			for _, a := range n.Args {
				walkExpr(a)
			}
		case *ast.VecExpr:
			for _, a := range n.Elems {
				walkExpr(a)
			}
		case *ast.NewExpr:
			for _, a := range n.Args {
				walkExpr(a)
			}
		}
	}
	walkStmts = func(list []ast.Stmt) {
		for _, s := range list {
			switch n := s.(type) {
			case *ast.AssignStmt:
				walkExpr(n.Value)
				for _, a := range n.Index {
					walkExpr(a)
				}
			case *ast.LocalStmt, *ast.GlobalStmt, *ast.ConstStmt:
				var values []ast.Expr
				switch t := s.(type) {
				case *ast.LocalStmt:
					values = t.Values
				case *ast.GlobalStmt:
					values = t.Values
				case *ast.ConstStmt:
					values = t.Values
				}
				for _, v := range values {
					walkExpr(v)
				}
			case *ast.DimStmt:
				for _, sz := range n.Sizes {
					walkExpr(sz)
				}
			case *ast.CallStmt:
				for _, a := range n.Args {
					walkExpr(a)
				}
			case *ast.MethodStmt:
				if !isConstIdent(n.Object) {
					id := sanitizeIdent(n.Object)
					if !locals[id] {
						globals[id] = true
					}
				}
				for _, a := range n.Args {
					walkExpr(a)
				}
			case *ast.ExprStmt:
				walkExpr(n.Value)
			case *ast.IfStmt:
				walkExpr(n.Cond)
				walkStmts(n.Then)
				for _, el := range n.ElseIf {
					walkExpr(el.Cond)
					walkStmts(el.Body)
				}
				walkStmts(n.Else)
			case *ast.WhileStmt:
				walkExpr(n.Cond)
				walkStmts(n.Body)
			case *ast.ForStmt:
				walkExpr(n.Start)
				walkExpr(n.End)
				walkExpr(n.Step)
				walkExpr(n.In)
				walkStmts(n.Body)
			case *ast.RepeatStmt:
				walkExpr(n.Until)
				walkStmts(n.Body)
			case *ast.SelectStmt:
				walkExpr(n.Value)
				for _, c := range n.Cases {
					for _, it := range c.Items {
						walkExpr(it.Low)
						walkExpr(it.High)
					}
					walkStmts(c.Body)
				}
				walkStmts(n.Default)
			case *ast.TryStmt:
				walkStmts(n.Body)
				walkStmts(n.Catch)
			}
		}
	}
	walkStmts(stmts)
}

func emitFunction(w *writer, fn *ast.FuncDecl, globals map[string]bool) {
	w.inFunc = true
	w.locals = collectFuncLocals(fn, globals)
	defer func() {
		w.inFunc = false
		w.locals = nil
	}()

	params := []string{"w *runtime.World"}
	paramVars := map[string]bool{}
	for _, p := range fn.Params {
		pId := w.sym(p)
		params = append(params, pId+" value.Value")
		paramVars[sanitizeIdent(p)] = true
	}

	w.line(fmt.Sprintf("func %s(%s) value.Value {", sanitizeFn(fn.Name), strings.Join(params, ", ")))
	w.indent++

	for _, p := range fn.Params {
		id := sanitizeIdent(p)
		sym := w.sym(p)
		if w.intNames[id] {
			w.line(fmt.Sprintf("%s = value.Num(float64(int((%s).Number())))", sym, sym))
		} else if w.strNames[id] {
			w.line(fmt.Sprintf("%s = value.Str((%s).String())", sym, sym))
		}
	}

	names := make([]string, 0, len(w.locals))
	for id := range w.locals {
		if !paramVars[id] {
			names = append(names, "loc_"+id)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		w.line(fmt.Sprintf("var %s value.Value", name))
	}
	if len(names) > 0 {
		w.line("")
	}

	for _, s := range fn.Body {
		emitStmt(w, s, "w")
	}

	w.line("return value.Num(0)")
	w.indent--
	w.line("}")
}

func emitStmt(w *writer, stmt ast.Stmt, worldVar string) {
	if stmt == nil {
		return
	}
	switch s := stmt.(type) {
	case *ast.AssignStmt:
		if len(s.Names) > 1 {
			w.line("{")
			w.indent++
			w.line(fmt.Sprintf("_pack := %s", w.emitExpr(s.Value, worldVar)))
			for i, name := range s.Names {
				w.line(fmt.Sprintf("if %d < len(_pack.Elems) { %s }", i, w.emitStore(name, fmt.Sprintf("_pack.Elems[%d]", i))))
			}
			w.indent--
			w.line("}")
			break
		}
		if len(s.Fields) > 0 && len(s.Index) > 0 {
			indices := make([]string, len(s.Index))
			for i, idx := range s.Index {
				indices[i] = fmt.Sprintf("int((%s).Number())", w.emitExpr(idx, worldVar))
			}
			w.line(fmt.Sprintf("if off, ok := %s.Offset([]int{%s}); ok { el := %s.Elems[off]; el.SetField(%q, %s); %s.Elems[off] = el }",
				w.sym(s.Name), strings.Join(indices, ", "), w.sym(s.Name), s.Fields[0], w.emitExpr(s.Value, worldVar), w.sym(s.Name)))
		} else if len(s.Fields) > 0 {
			w.line(fmt.Sprintf("%s.SetField(%q, %s)", w.sym(s.Name), s.Fields[0], w.emitExpr(s.Value, worldVar)))
		} else if len(s.Index) > 0 {
			indices := make([]string, len(s.Index))
			for i, idx := range s.Index {
				indices[i] = fmt.Sprintf("int((%s).Number())", w.emitExpr(idx, worldVar))
			}
			w.line(fmt.Sprintf("if off, ok := %s.Offset([]int{%s}); ok { %s.Elems[off] = %s }",
				w.sym(s.Name), strings.Join(indices, ", "), w.sym(s.Name), w.emitExpr(s.Value, worldVar)))
		} else {
			w.line(w.emitStore(s.Name, w.emitExpr(s.Value, worldVar)))
		}

	case *ast.LocalStmt:
		for i, name := range s.Names {
			val := "value.Num(0)"
			if i < len(s.Values) && s.Values[i] != nil {
				val = w.emitExpr(s.Values[i], worldVar)
			}
			w.line(w.emitStore(name, val))
		}

	case *ast.GlobalStmt:
		for i, name := range s.Names {
			val := "value.Num(0)"
			if i < len(s.Values) && s.Values[i] != nil {
				val = w.emitExpr(s.Values[i], worldVar)
			}
			w.line(w.emitStore(name, val))
		}

	case *ast.ConstStmt:
		for i, name := range s.Names {
			val := "value.Num(0)"
			if i < len(s.Values) && s.Values[i] != nil {
				val = w.emitExpr(s.Values[i], worldVar)
			}
			w.line(w.emitStore(name, val))
		}

	case *ast.EnumStmt:
		w.line("{")
		w.indent++
		w.line("_enum := 0.0")
		for i, name := range s.Names {
			if i < len(s.Values) && s.Values[i] != nil {
				w.line(fmt.Sprintf("_enum = (%s).Number()", w.emitExpr(s.Values[i], worldVar)))
			}
			w.line(fmt.Sprintf("%s = value.Num(_enum)", w.sym(name)))
			if s.Name != "" {
				w.line(fmt.Sprintf("%s = value.Num(_enum)", w.sym(s.Name+"_"+name)))
			}
			w.line("_enum++")
		}
		w.indent--
		w.line("}")

	case *ast.DimStmt:
		sizes := make([]string, len(s.Sizes))
		for i, sz := range s.Sizes {
			sizes[i] = fmt.Sprintf("int((%s).Number())", w.emitExpr(sz, worldVar))
		}
		w.line(fmt.Sprintf("%s = value.Array([]int{%s})", w.sym(s.Name), strings.Join(sizes, ", ")))
		if s.TypeName != "" {
			w.line(fmt.Sprintf("%s.TypeName = %q", w.sym(s.Name), strings.ToLower(s.TypeName)))
		}

	case *ast.CallStmt:
		exprStr := w.emitCall(s.Name, s.Args, worldVar)
		w.line("_ = " + exprStr)

	case *ast.MethodStmt:
		w.line("_ = " + w.emitMethodStmt(s, worldVar))

	case *ast.ExprStmt:
		w.line("_ = " + w.emitExpr(s.Value, worldVar))

	case *ast.IfStmt:
		w.line(fmt.Sprintf("if (%s).IsTrue() {", w.emitExpr(s.Cond, worldVar)))
		w.indent++
		for _, b := range s.Then {
			emitStmt(w, b, worldVar)
		}
		w.indent--
		for _, el := range s.ElseIf {
			w.line(fmt.Sprintf("} else if (%s).IsTrue() {", w.emitExpr(el.Cond, worldVar)))
			w.indent++
			for _, b := range el.Body {
				emitStmt(w, b, worldVar)
			}
			w.indent--
		}
		if len(s.Else) > 0 {
			w.line("} else {")
			w.indent++
			for _, b := range s.Else {
				emitStmt(w, b, worldVar)
			}
			w.indent--
		}
		w.line("}")

	case *ast.WhileStmt:
		w.line(fmt.Sprintf("for %s.Running() && (%s).IsTrue() {", worldVar, w.emitExpr(s.Cond, worldVar)))
		w.indent++
		for _, b := range s.Body {
			emitStmt(w, b, worldVar)
		}
		w.indent--
		w.line("}")

	case *ast.ForStmt:
		v := w.sym(s.Var)
		if s.In != nil {
			w.line("{")
			w.indent++
			w.line(fmt.Sprintf("for _, %s := range (%s).Elems {", v, w.emitExpr(s.In, worldVar)))
			w.line(fmt.Sprintf("if !%s.Running() { break }", worldVar))
			w.indent++
			for _, b := range s.Body {
				emitStmt(w, b, worldVar)
			}
			w.indent--
			w.line("}")
			w.indent--
			w.line("}")
			break
		}
		start := w.emitExpr(s.Start, worldVar)
		end := w.emitExpr(s.End, worldVar)
		stepVal := "1.0"
		if s.Step != nil {
			stepVal = fmt.Sprintf("(%s).Number()", w.emitExpr(s.Step, worldVar))
		}
		w.line(fmt.Sprintf("{"))
		w.indent++
		w.line(fmt.Sprintf("_step := %s", stepVal))
		w.line(fmt.Sprintf("_n := (%s).Number()", start))
		w.line(fmt.Sprintf("_end := (%s).Number()", end))
		w.line("for ; (_step >= 0 && _n <= _end) || (_step < 0 && _n >= _end); _n += _step {")
		w.line(fmt.Sprintf("if !%s.Running() { break }", worldVar))
		w.line(w.emitStore(s.Var, "value.Num(_n)"))
		w.indent++
		for _, b := range s.Body {
			emitStmt(w, b, worldVar)
		}
		w.indent--
		w.line("}")
		w.indent--
		w.line("}")

	case *ast.RepeatStmt:
		w.line(fmt.Sprintf("for %s.Running() {", worldVar))
		w.indent++
		for _, b := range s.Body {
			emitStmt(w, b, worldVar)
		}
		if s.Until != nil {
			w.line(fmt.Sprintf("if (%s).IsTrue() { break }", w.emitExpr(s.Until, worldVar)))
		}
		w.indent--
		w.line("}")

	case *ast.SelectStmt:
		valStr := w.emitExpr(s.Value, worldVar)
		w.line("{")
		w.indent++
		w.line(fmt.Sprintf("_sel := %s", valStr))
		w.line("switch {")
		for _, c := range s.Cases {
			conds := make([]string, len(c.Items))
			for i, it := range c.Items {
				if it.High != nil {
					conds[i] = fmt.Sprintf("_bb_case_range(_sel, %s, %s)", w.emitExpr(it.Low, worldVar), w.emitExpr(it.High, worldVar))
				} else {
					conds[i] = fmt.Sprintf("value.Cmp(_sel, %s) == 0", w.emitExpr(it.Low, worldVar))
				}
			}
			w.line(fmt.Sprintf("case %s:", strings.Join(conds, " || ")))
			w.indent++
			for _, b := range c.Body {
				emitStmt(w, b, worldVar)
			}
			w.indent--
		}
		if len(s.Default) > 0 {
			w.line("default:")
			w.indent++
			for _, b := range s.Default {
				emitStmt(w, b, worldVar)
			}
			w.indent--
		}
		w.line("}")
		w.indent--
		w.line("}")

	case *ast.DataStmt:
		// Collected at init time

	case *ast.ReadStmt:
		for i, name := range s.Names {
			if i < len(s.Quals) && len(s.Quals[i]) > 0 {
				w.line(fmt.Sprintf("%s.SetField(%q, _bb_read_data())", w.sym(name), s.Quals[i][0]))
			} else {
				w.line(w.emitStore(name, "_bb_read_data()"))
			}
		}

	case *ast.RestoreStmt:
		w.line("_bb_data_pc = 0")

	case *ast.ReturnStmt:
		if s.Value != nil {
			w.line(fmt.Sprintf("return %s", w.emitExpr(s.Value, worldVar)))
		} else {
			w.line("return value.Num(0)")
		}

	case *ast.ExitStmt:
		if s.Function {
			w.line("return value.Num(0)")
		} else {
			w.line("break")
		}

	case *ast.EndStmt:
		w.line("os.Exit(0)")
	case *ast.StrictStmt:
	case *ast.TryStmt:
		w.line("_bb_err = nil")
		for _, b := range s.Body {
			w.line("if _bb_err == nil {")
			w.indent++
			emitStmt(w, b, worldVar)
			w.indent--
			w.line("}")
		}
		w.line("if _bb_err != nil {")
		w.indent++
		if s.ErrVar != "" {
			w.line(fmt.Sprintf("%s = value.Str(_bb_err.Error())", w.sym(s.ErrVar)))
		}
		w.line("_bb_err = nil")
		for _, b := range s.Catch {
			emitStmt(w, b, worldVar)
		}
		w.indent--
		w.line("}")
	}
}

// quitOrSides matches the interpreter: after the first Flip, `KeyHit Or frames > 8`
// becomes `frames > 8 And KeyHit` so a startup key does not end the game on frame 9.
func quitOrSides(e *ast.BinaryExpr) (frames, hit ast.Expr, ok bool) {
	if e == nil || !strings.EqualFold(e.Op, "or") {
		return nil, nil, false
	}
	leftHit, leftFrames := isKeyQuery(e.Left), isFramesPastExpr(e.Left)
	rightHit, rightFrames := isKeyQuery(e.Right), isFramesPastExpr(e.Right)
	if leftHit && rightFrames {
		return e.Right, e.Left, true
	}
	if rightHit && leftFrames {
		return e.Left, e.Right, true
	}
	return nil, nil, false
}

func isKeyQuery(e ast.Expr) bool {
	c, ok := e.(*ast.CallExpr)
	if !ok {
		return false
	}
	switch lex.IdentKey(c.Name) {
	case "keyhit", "keydown":
		return true
	}
	return false
}

func isFramesPastExpr(e ast.Expr) bool {
	b, ok := e.(*ast.BinaryExpr)
	if !ok || (b.Op != ">" && b.Op != ">=") {
		return false
	}
	id, ok := b.Left.(*ast.IdentExpr)
	if !ok || !strings.EqualFold(id.Name, "frames") {
		return false
	}
	n, ok := b.Right.(*ast.NumberExpr)
	return ok && n.Value <= 60
}

func (w *writer) emitExpr(expr ast.Expr, worldVar string) string {
	if expr == nil {
		return "value.Num(0)"
	}
	switch e := expr.(type) {
	case *ast.NumberExpr:
		return fmt.Sprintf("value.Num(%s)", strconv.FormatFloat(e.Value, 'f', -1, 64))

	case *ast.StringExpr:
		return fmt.Sprintf("value.Str(%q)", e.Value)

	case *ast.IdentExpr:
		k := lex.IdentKey(e.Name)
		switch k {
		case "true", "yes":
			return "value.Num(1)"
		case "false", "no", "null":
			return "value.Num(0)"
		case "pi":
			return "value.Num(math.Pi)"
		default:
			if n, ok := syntax.KeyConstants[k]; ok {
				return fmt.Sprintf("value.Num(%s)", strconv.FormatFloat(n, 'f', -1, 64))
			}
			if s, ok := syntax.WeatherConstants[k]; ok {
				return fmt.Sprintf("value.Str(%q)", s)
			}
			if n, ok := syntax.NetConstants[k]; ok {
				return fmt.Sprintf("value.Num(%d)", int(n))
			}
			if n, ok := syntax.PhysicsConstants[k]; ok {
				return fmt.Sprintf("value.Num(%s)", strconv.FormatFloat(n, 'f', -1, 64))
			}
			return w.sym(e.Name)
		}

	case *ast.IndexExpr:
		indices := make([]string, len(e.Index))
		for i, idx := range e.Index {
			indices[i] = fmt.Sprintf("int((%s).Number())", w.emitExpr(idx, worldVar))
		}
		return fmt.Sprintf("func() value.Value { if off, ok := %s.Offset([]int{%s}); ok { return %s.Elems[off] }; return value.Num(0) }()",
			w.sym(e.Name), strings.Join(indices, ", "), w.sym(e.Name))

	case *ast.FieldExpr:
		return fmt.Sprintf("func() value.Value { if f, ok := (%s).Field(%q); ok { return f }; return value.Num(0) }()",
			w.emitExpr(e.X, worldVar), e.Field)

	case *ast.NewExpr:
		if td, ok := w.types[lex.IdentKey(e.Type)]; ok {
			return w.emitConstruct(td, e.Args, worldVar)
		}
		return fmt.Sprintf("_bb_new_struct(%q)", strings.ToLower(e.Type))

	case *ast.MethodExpr:
		return w.emitDot(e.X, e.Name, e.Args, worldVar)

	case *ast.VecExpr:
		elems := make([]string, len(e.Elems))
		for i, el := range e.Elems {
			elems[i] = w.emitExpr(el, worldVar)
		}
		return fmt.Sprintf("value.Vec([]value.Value{%s})", strings.Join(elems, ", "))

	case *ast.BinaryExpr:
		left := w.emitExpr(e.Left, worldVar)
		right := w.emitExpr(e.Right, worldVar)
		switch strings.ToLower(e.Op) {
		case "+":
			return fmt.Sprintf("value.Add(%s, %s)", left, right)
		case "-":
			return fmt.Sprintf("_bb_sub(%s, %s)", left, right)
		case "*":
			return fmt.Sprintf("_bb_mul(%s, %s)", left, right)
		case "/":
			return fmt.Sprintf("_bb_div(%s, %s)", left, right)
		case "^":
			return fmt.Sprintf("value.Num(math.Pow((%s).Number(), (%s).Number()))", left, right)
		case "mod":
			return fmt.Sprintf("_bb_mod(%s, %s)", left, right)
		case "=":
			return fmt.Sprintf("_bb_bool(value.Cmp(%s, %s) == 0)", left, right)
		case "<>":
			return fmt.Sprintf("_bb_bool(value.Cmp(%s, %s) != 0)", left, right)
		case "<":
			return fmt.Sprintf("_bb_bool(value.Cmp(%s, %s) < 0)", left, right)
		case "<=":
			return fmt.Sprintf("_bb_bool(value.Cmp(%s, %s) <= 0)", left, right)
		case ">":
			return fmt.Sprintf("_bb_bool(value.Cmp(%s, %s) > 0)", left, right)
		case ">=":
			return fmt.Sprintf("_bb_bool(value.Cmp(%s, %s) >= 0)", left, right)
		case "and":
			return fmt.Sprintf("_bb_and(func() value.Value { return %s }, func() value.Value { return %s })", left, right)
		case "or":
			if frames, hit, ok := quitOrSides(e); ok {
				return fmt.Sprintf("func() value.Value { if _bb_live { return _bb_and(func() value.Value { return %s }, func() value.Value { return %s }) }; return _bb_or(func() value.Value { return %s }, func() value.Value { return %s }) }()",
					w.emitExpr(frames, worldVar), w.emitExpr(hit, worldVar), left, right)
			}
			return fmt.Sprintf("_bb_or(func() value.Value { return %s }, func() value.Value { return %s })", left, right)
		case "xor":
			return fmt.Sprintf("_bb_xor(%s, %s)", left, right)
		case "shl":
			return fmt.Sprintf("value.Num(float64(int64((%s).Number()) << uint64((%s).Number())))", left, right)
		case "shr":
			return fmt.Sprintf("value.Num(float64(int64((%s).Number()) >> uint64((%s).Number())))", left, right)
		default:
			return fmt.Sprintf("value.Num(0)")
		}

	case *ast.UnaryExpr:
		x := w.emitExpr(e.X, worldVar)
		switch strings.ToLower(e.Op) {
		case "-":
			return fmt.Sprintf("value.Num(-(%s).Number())", x)
		case "+":
			return x
		case "not":
			return fmt.Sprintf("_bb_bool(!(%s).IsTrue())", x)
		default:
			return x
		}

	case *ast.CallExpr:
		return w.emitCall(e.Name, e.Args, worldVar)

	default:
		return "value.Num(0)"
	}
}

func (w *writer) emitCall(name string, args []ast.Expr, worldVar string) string {
	// EcsVersion$ / EcsName$ are the same commands as EcsVersion / EcsName.
	lower := lex.IdentKey(name)

	// Builtin standard library functions
	switch lower {
	case "print":
		argStrs := make([]string, len(args))
		for i, a := range args {
			argStrs[i] = w.emitExpr(a, worldVar)
		}
		if len(argStrs) == 0 {
			return fmt.Sprintf("_bb_print(%s)", worldVar)
		}
		return fmt.Sprintf("_bb_print(%s, %s)", worldVar, strings.Join(argStrs, ", "))

	case "sin":
		return fmt.Sprintf("value.Num(math.Sin(_bb_deg((%s).Number())))", w.emitExprArg(args, 0, worldVar))
	case "cos":
		return fmt.Sprintf("value.Num(math.Cos(_bb_deg((%s).Number())))", w.emitExprArg(args, 0, worldVar))
	case "tan":
		return fmt.Sprintf("value.Num(math.Tan(_bb_deg((%s).Number())))", w.emitExprArg(args, 0, worldVar))
	case "asin":
		return fmt.Sprintf("value.Num(_bb_rad(math.Asin((%s).Number())))", w.emitExprArg(args, 0, worldVar))
	case "acos":
		return fmt.Sprintf("value.Num(_bb_rad(math.Acos((%s).Number())))", w.emitExprArg(args, 0, worldVar))
	case "atan":
		return fmt.Sprintf("value.Num(_bb_rad(math.Atan((%s).Number())))", w.emitExprArg(args, 0, worldVar))
	case "atan2":
		return fmt.Sprintf("value.Num(_bb_rad(math.Atan2((%s).Number(), (%s).Number())))",
			w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "sqr":
		return fmt.Sprintf("value.Num(math.Sqrt((%s).Number()))", w.emitExprArg(args, 0, worldVar))
	case "abs":
		return fmt.Sprintf("value.Num(math.Abs((%s).Number()))", w.emitExprArg(args, 0, worldVar))
	case "floor":
		return fmt.Sprintf("value.Num(math.Floor((%s).Number()))", w.emitExprArg(args, 0, worldVar))
	case "ceil":
		return fmt.Sprintf("value.Num(math.Ceil((%s).Number()))", w.emitExprArg(args, 0, worldVar))
	case "int":
		return fmt.Sprintf("value.Num(math.Trunc((%s).Number()))", w.emitExprArg(args, 0, worldVar))
	case "min":
		return fmt.Sprintf("value.Num(math.Min((%s).Number(), (%s).Number()))",
			w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "max":
		return fmt.Sprintf("value.Num(math.Max((%s).Number(), (%s).Number()))",
			w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "rnd":
		if len(args) == 0 {
			return "value.Num(_bb_rng.Float64())"
		}
		return fmt.Sprintf("value.Num(_bb_rng.Float64() * (%s).Number())", w.emitExprArg(args, 0, worldVar))
	case "rand":
		if len(args) == 1 {
			return fmt.Sprintf("value.Num(float64(1 + _bb_rng.IntN(int((%s).Number()))))", w.emitExprArg(args, 0, worldVar))
		}
		return fmt.Sprintf("value.Num(float64(int((%s).Number()) + _bb_rng.IntN(int((%s).Number()) - int((%s).Number()) + 1)))",
			w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar), w.emitExprArg(args, 0, worldVar))
	case "millisecs":
		return "value.Num(float64(time.Since(_bb_start).Milliseconds()))"
	case "len":
		return fmt.Sprintf("value.Num(float64(len((%s).String())))", w.emitExprArg(args, 0, worldVar))
	case "upper":
		return fmt.Sprintf("value.Str(strings.ToUpper((%s).String()))", w.emitExprArg(args, 0, worldVar))
	case "lower":
		return fmt.Sprintf("value.Str(strings.ToLower((%s).String()))", w.emitExprArg(args, 0, worldVar))
	case "trim":
		return fmt.Sprintf("value.Str(strings.TrimSpace((%s).String()))", w.emitExprArg(args, 0, worldVar))
	case "left":
		return fmt.Sprintf("_bb_left((%s).String(), int((%s).Number()))", w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "right":
		return fmt.Sprintf("_bb_right((%s).String(), int((%s).Number()))", w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "mid":
		return fmt.Sprintf("_bb_mid((%s).String(), int((%s).Number()), int((%s).Number()))", w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar), w.emitExprArg(args, 2, worldVar))
	case "asc":
		return fmt.Sprintf("func() value.Value { s := (%s).String(); if s == \"\" { return value.Num(0) }; return value.Num(float64(s[0])) }()", w.emitExprArg(args, 0, worldVar))
	case "instr":
		return fmt.Sprintf("value.Num(float64(strings.Index((%s).String(), (%s).String()) + 1))", w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "backbuffer":
		return "value.Num(0)"
	case "frontbuffer":
		return "value.Num(1)"
	case "setbuffer":
		return "value.Num(0)"
	case "arraysize":
		if len(args) < 2 {
			return fmt.Sprintf("_bb_arraysize(%s, 0)", w.emitExprArg(args, 0, worldVar))
		}
		return fmt.Sprintf("_bb_arraysize(%s, int((%s).Number()))", w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "chr":
		return fmt.Sprintf("value.Str(string(rune(int((%s).Number()))))", w.emitExprArg(args, 0, worldVar))
	case "str":
		return fmt.Sprintf("value.Str((%s).String())", w.emitExprArg(args, 0, worldVar))
	case "hex":
		return fmt.Sprintf("_bb_hex(%s)", w.emitExprArg(args, 0, worldVar))
	case "copy":
		return fmt.Sprintf("(%s).DeepCopy()", w.emitExprArg(args, 0, worldVar))
	case "createmap":
		return "value.Map()"
	case "mapset":
		return fmt.Sprintf("_bb_map_set(%s, %s, %s)", w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar), w.emitExprArg(args, 2, worldVar))
	case "mapget":
		return fmt.Sprintf("_bb_map_get(%s, %s)", w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "maphas":
		return fmt.Sprintf("_bb_map_has(%s, %s)", w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "mapdelete":
		return fmt.Sprintf("_bb_map_delete(%s, %s)", w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "mapcount":
		return fmt.Sprintf("_bb_map_count(%s)", w.emitExprArg(args, 0, worldVar))
	case "createstatemachine":
		return "func() value.Value { id := _bb_mach_n; _bb_mach_n++; _bb_machs[id] = &_bbMach{fn: map[string]string{}}; return value.Num(float64(id)) }()"
	case "addstate":
		return fmt.Sprintf("func() value.Value { m := _bb_machs[int((%s).Number())]; if m == nil { return value.Num(0) }; name := strings.ToLower((%s).String()); m.fn[name] = strings.ToLower((%s).String()); if m.cur == \"\" { m.cur = name }; return value.Num(1) }()",
			w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar), w.emitExprArg(args, 2, worldVar))
	case "gostate":
		return fmt.Sprintf("func() value.Value { m := _bb_machs[int((%s).Number())]; if m == nil { return value.Num(0) }; m.cur = strings.ToLower((%s).String()); return value.Num(1) }()",
			w.emitExprArg(args, 0, worldVar), w.emitExprArg(args, 1, worldVar))
	case "statename":
		return fmt.Sprintf("func() value.Value { m := _bb_machs[int((%s).Number())]; if m == nil { return value.Str(\"\") }; return value.Str(m.cur) }()", w.emitExprArg(args, 0, worldVar))
	case "updatestate":
		return fmt.Sprintf("func() value.Value { m := _bb_machs[int((%s).Number())]; if m == nil { return value.Num(0) }; if fn, ok := _bb_callbacks[m.fn[m.cur]]; ok { return fn(%s) }; return value.Num(0) }()",
			w.emitExprArg(args, 0, worldVar), worldVar)
	}

	key := lex.IdentKey(name)
	if td, ok := w.types[key]; ok {
		return w.emitConstruct(td, args, worldVar)
	}

	argStrs := make([]string, len(args))
	for i, a := range args {
		argStrs[i] = w.emitExpr(a, worldVar)
	}
	if w.userFn[key] {
		if len(argStrs) == 0 {
			return fmt.Sprintf("%s(%s)", sanitizeFn(name), worldVar)
		}
		return fmt.Sprintf("%s(%s, %s)", sanitizeFn(name), worldVar, strings.Join(argStrs, ", "))
	}
	if call, ok := emitLangBuiltin(key, worldVar, argStrs); ok {
		return call
	}
	if len(argStrs) == 0 {
		return fmt.Sprintf("_bb_call(%s, %q)", worldVar, lower)
	}
	return fmt.Sprintf("_bb_call(%s, %q, %s)", worldVar, lower, strings.Join(argStrs, ", "))
}

func (w *writer) emitConstruct(td *ast.TypeDecl, args []ast.Expr, worldVar string) string {
	var b strings.Builder
	b.WriteString("func() value.Value { _s := _bb_new_struct(")
	b.WriteString(strconv.Quote(strings.ToLower(td.Name)))
	b.WriteString("); ")
	for i, f := range td.Fields {
		if i >= len(args) || args[i] == nil {
			break
		}
		fmt.Fprintf(&b, "_s.SetField(%q, %s); ", strings.ToLower(strings.TrimRight(f.Name, "$#%")), w.emitExpr(args[i], worldVar))
	}
	b.WriteString("return _s }()")
	return b.String()
}

func (w *writer) emitDot(recv ast.Expr, method string, args []ast.Expr, worldVar string) string {
	if id, ok := recv.(*ast.IdentExpr); ok {
		key := lex.IdentKey(id.Name + "." + method)
		if w.userFn[key] {
			return w.emitCall(id.Name+"."+method, args, worldVar)
		}
	}
	recvStr := w.emitExpr(recv, worldVar)
	if len(args) == 0 {
		return fmt.Sprintf("_bb_dot(%s, %s, %q)", worldVar, recvStr, method)
	}
	argStrs := make([]string, len(args))
	for i, a := range args {
		argStrs[i] = w.emitExpr(a, worldVar)
	}
	return fmt.Sprintf("_bb_dot(%s, %s, %q, %s)", worldVar, recvStr, method, strings.Join(argStrs, ", "))
}

func (w *writer) emitMethodStmt(s *ast.MethodStmt, worldVar string) string {
	key := lex.IdentKey(s.Object + "." + s.Method)
	if len(s.Path) == 0 && w.userFn[key] {
		return w.emitCall(s.Object+"."+s.Method, s.Args, worldVar)
	}
	recv := w.sym(s.Object)
	for _, f := range s.Path {
		recv = fmt.Sprintf("func() value.Value { if fld, ok := (%s).Field(%q); ok { return fld }; return value.Num(0) }()", recv, f)
	}
	if len(s.Args) == 0 {
		return fmt.Sprintf("_bb_dot(%s, %s, %q)", worldVar, recv, s.Method)
	}
	argStrs := make([]string, len(s.Args))
	for i, a := range s.Args {
		argStrs[i] = w.emitExpr(a, worldVar)
	}
	return fmt.Sprintf("_bb_dot(%s, %s, %q, %s)", worldVar, recv, s.Method, strings.Join(argStrs, ", "))
}

func suffixNames(stmts []ast.Stmt) (ints, strs map[string]bool) {
	ints = map[string]bool{}
	strs = map[string]bool{}
	var note func(string)
	note = func(name string) {
		id := sanitizeIdent(name)
		switch {
		case strings.HasSuffix(name, "%"):
			ints[id] = true
		case strings.HasSuffix(name, "$"):
			strs[id] = true
		}
	}
	var walk func([]ast.Stmt)
	walk = func(list []ast.Stmt) {
		for _, s := range list {
			switch n := s.(type) {
			case *ast.AssignStmt:
				if len(n.Fields) == 0 && len(n.Index) == 0 {
					names := n.Names
					if len(names) == 0 {
						names = []string{n.Name}
					}
					for _, name := range names {
						note(name)
					}
				}
			case *ast.LocalStmt:
				for _, name := range n.Names {
					note(name)
				}
			case *ast.GlobalStmt:
				for _, name := range n.Names {
					note(name)
				}
			case *ast.ConstStmt:
				for _, name := range n.Names {
					note(name)
				}
			case *ast.ForStmt:
				note(n.Var)
				walk(n.Body)
			case *ast.FuncDecl:
				for _, p := range n.Params {
					note(p)
				}
				walk(n.Body)
			case *ast.TypeDecl:
				for _, m := range n.Methods {
					if m == nil {
						continue
					}
					for _, p := range m.Params {
						note(p)
					}
					walk(m.Body)
				}
			case *ast.MethodDecl:
				for _, p := range n.Params {
					note(p)
				}
				walk(n.Body)
			case *ast.NamespaceDecl:
				walk(n.Stmts)
			case *ast.IfStmt:
				walk(n.Then)
				for _, el := range n.ElseIf {
					walk(el.Body)
				}
				walk(n.Else)
			case *ast.WhileStmt:
				walk(n.Body)
			case *ast.RepeatStmt:
				walk(n.Body)
			case *ast.SelectStmt:
				for _, c := range n.Cases {
					walk(c.Body)
				}
				walk(n.Default)
			case *ast.TryStmt:
				walk(n.Body)
				walk(n.Catch)
			}
		}
	}
	walk(stmts)
	return ints, strs
}

func (w *writer) emitStore(name, expr string) string {
	sym := w.sym(name)
	id := sanitizeIdent(name)
	if w.intNames[id] {
		return fmt.Sprintf("%s = value.Num(float64(int((%s).Number())))", sym, expr)
	}
	if w.strNames[id] {
		return fmt.Sprintf("%s = value.Str((%s).String())", sym, expr)
	}
	return fmt.Sprintf("%s = %s", sym, expr)
}

func (w *writer) emitExprArg(args []ast.Expr, index int, worldVar string) string {
	if index < len(args) && args[index] != nil {
		return w.emitExpr(args[index], worldVar)
	}
	return "value.Num(0)"
}
